using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Volo.Abp.Domain.Repositories;

namespace ToksozBysNew.VisitDailyActions
{
    public interface IVisitDailyActionRepository : IRepository<VisitDailyAction, Guid>
    {
        Task<VisitDailyActionWithNavigationProperties> GetWithNavigationPropertiesAsync(
    Guid id,
    CancellationToken cancellationToken = default
);

        Task<List<VisitDailyActionWithNavigationProperties>> GetListWithNavigationPropertiesAsync(
            string filterText = null,
            DateTime? visitDailyDateMin = null,
            DateTime? visitDailyDateMax = null,
            decimal? visitDaily1Min = null,
            decimal? visitDaily1Max = null,
            decimal? visitDaily2Min = null,
            decimal? visitDaily2Max = null,
            decimal? visitDaily3Min = null,
            decimal? visitDaily3Max = null,
            decimal? visitDaily4Min = null,
            decimal? visitDaily4Max = null,
            decimal? visitDaily5Min = null,
            decimal? visitDaily5Max = null,
            decimal? visitDaily6Min = null,
            decimal? visitDaily6Max = null,
            decimal? visitDaily7Min = null,
            decimal? visitDaily7Max = null,
            decimal? visitDaily8Min = null,
            decimal? visitDaily8Max = null,
            decimal? visitDaily9Min = null,
            decimal? visitDaily9Max = null,
            decimal? visitDaily10Min = null,
            decimal? visitDaily10Max = null,
            decimal? visitDaily11Min = null,
            decimal? visitDaily11Max = null,
            decimal? visitDaily12Min = null,
            decimal? visitDaily12Max = null,
            decimal? visitDaily13Min = null,
            decimal? visitDaily13Max = null,
            decimal? visitDaily14Min = null,
            decimal? visitDaily14Max = null,
            decimal? visitDaily15Min = null,
            decimal? visitDaily15Max = null,
            DateTime? visitDailyCloseDateMin = null,
            DateTime? visitDailyCloseDateMax = null,
            string visitDailyNote = null,
            Guid? identityUserId = null,
            string sorting = null,
            int maxResultCount = int.MaxValue,
            int skipCount = 0,
            CancellationToken cancellationToken = default
        );

        Task<List<VisitDailyAction>> GetListAsync(
                    string filterText = null,
                    DateTime? visitDailyDateMin = null,
                    DateTime? visitDailyDateMax = null,
                    decimal? visitDaily1Min = null,
                    decimal? visitDaily1Max = null,
                    decimal? visitDaily2Min = null,
                    decimal? visitDaily2Max = null,
                    decimal? visitDaily3Min = null,
                    decimal? visitDaily3Max = null,
                    decimal? visitDaily4Min = null,
                    decimal? visitDaily4Max = null,
                    decimal? visitDaily5Min = null,
                    decimal? visitDaily5Max = null,
                    decimal? visitDaily6Min = null,
                    decimal? visitDaily6Max = null,
                    decimal? visitDaily7Min = null,
                    decimal? visitDaily7Max = null,
                    decimal? visitDaily8Min = null,
                    decimal? visitDaily8Max = null,
                    decimal? visitDaily9Min = null,
                    decimal? visitDaily9Max = null,
                    decimal? visitDaily10Min = null,
                    decimal? visitDaily10Max = null,
                    decimal? visitDaily11Min = null,
                    decimal? visitDaily11Max = null,
                    decimal? visitDaily12Min = null,
                    decimal? visitDaily12Max = null,
                    decimal? visitDaily13Min = null,
                    decimal? visitDaily13Max = null,
                    decimal? visitDaily14Min = null,
                    decimal? visitDaily14Max = null,
                    decimal? visitDaily15Min = null,
                    decimal? visitDaily15Max = null,
                    DateTime? visitDailyCloseDateMin = null,
                    DateTime? visitDailyCloseDateMax = null,
                    string visitDailyNote = null,
                    string sorting = null,
                    int maxResultCount = int.MaxValue,
                    int skipCount = 0,
                    CancellationToken cancellationToken = default
                );

        Task<long> GetCountAsync(
            string filterText = null,
            DateTime? visitDailyDateMin = null,
            DateTime? visitDailyDateMax = null,
            decimal? visitDaily1Min = null,
            decimal? visitDaily1Max = null,
            decimal? visitDaily2Min = null,
            decimal? visitDaily2Max = null,
            decimal? visitDaily3Min = null,
            decimal? visitDaily3Max = null,
            decimal? visitDaily4Min = null,
            decimal? visitDaily4Max = null,
            decimal? visitDaily5Min = null,
            decimal? visitDaily5Max = null,
            decimal? visitDaily6Min = null,
            decimal? visitDaily6Max = null,
            decimal? visitDaily7Min = null,
            decimal? visitDaily7Max = null,
            decimal? visitDaily8Min = null,
            decimal? visitDaily8Max = null,
            decimal? visitDaily9Min = null,
            decimal? visitDaily9Max = null,
            decimal? visitDaily10Min = null,
            decimal? visitDaily10Max = null,
            decimal? visitDaily11Min = null,
            decimal? visitDaily11Max = null,
            decimal? visitDaily12Min = null,
            decimal? visitDaily12Max = null,
            decimal? visitDaily13Min = null,
            decimal? visitDaily13Max = null,
            decimal? visitDaily14Min = null,
            decimal? visitDaily14Max = null,
            decimal? visitDaily15Min = null,
            decimal? visitDaily15Max = null,
            DateTime? visitDailyCloseDateMin = null,
            DateTime? visitDailyCloseDateMax = null,
            string visitDailyNote = null,
            Guid? identityUserId = null,
            CancellationToken cancellationToken = default);
    }
}